apiVersion: v1
kind: ConfigMap
metadata:
  name: env-smra-backend
  namespace: dev-smra
data:
  Example_Config: ""
  APP_NAME: "SritrangSmartReceive"
  APP_ENV: "local"
  APP_KEY: ""
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  APP_PORT: "3000"

  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: mssql
  DB_HOST: "10.254.1.2"
  DB_PORT: "30000"
  DB_DATABASE: SMRA
  DB_INSTANCE: devsql
  DB_USERNAME: dev-smra
  DB_PASSWORD: cFawxCVLmRGi.2022@D

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DRIVER: "local"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailtrap"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: L3WBKK6GD3CFUWHBIJKV
  AWS_SECRET_ACCESS_KEY: tPnDlYkwrTxy4PxBMRSBeoJWm4IsQNcqOslICYgv
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: sritrang-smra-dev
  AWS_ENDPOINT: s3gw.inet.co.th:8082
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_APP_CLUSTER: "mt1"

  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

  JWT_SECRET: "2c729fbe7f905dc71d9481f42bb703d5dfeb4123b58294a34e1ebf6f07a1a841"

  UPLOAD_DIR: "./upload"
