FROM node:16 as base

USER node

LABEL maintainer="Chayangkoon Tona <chayangkoontona@gmail.com>"

RUN mkdir /home/node/.npm-global ; \
  mkdir -p /home/node/app ; \
  chown -R node:node /home/node/app ; \
  chown -R node:node /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

WORKDIR /home/node/app

COPY package.json .

RUN npm i --production

COPY . .

FROM base as production

ENV PORT 8080

ENV NODE_PATH=./dist

RUN npm run build

# CMD [ "npm", "run", "prod" ]
