version: '3.7'

services:
  js-node-docker:
    # image: chayangkoontona/sritrangsmartreceive-js-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    restart: always
    container_name: sritrangsmartreceive-js-node
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm start